parameters:
#    keboola_syrup_extractor.example.class: Keboola\Juicer\Example
#     # Components
#     components:
#         ex-bundle:
#             bundle:  Keboola\Juicer\KeboolaJuicer

services:
    # FIXME - doesn't work in a bundle, has to be in the "child" bundle
    keboola_extractor.configuration:
        class: Keboola\Juicer\Common\Configuration
        arguments: [%app_name%, @syrup.encryptor, @syrup.temp]

