languages:
  PHP: true
  exclude_paths:
  - "vendor"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
    exclude_paths:
      - Tests/      
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      Naming/ShortVariable:
        enabled: false 
      Naming/LongVariable:
        enabled: false