language: php
php:
  - 7.0

before_install:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - ./vendor/bin/phpstan analyse --level=4 Client Common Config Exception Extractor Filesystem Pagination Parser Tests || true
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

notifications:
  email: false
  slack: keboola:xNrfNET99b2wBdiF2pbOH3x6